name = "hellonextjs"
compatibility_date = "2023-12-18"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

# Pages 配置
pages_build_output_dir = ".vercel/output/static"

[[pages]]
functions = ".vercel/output/functions" 